export const FourthSectionDatas = [
  {
    id: 1,
    image: "../assests/FourthSection/donate-1-1.png",
    imageText: "CHARITY",
    heading: "Give African Child A Good Education",
    text: "Street children are poor or home children who live on the streets ",
    percentage: "64",
    raised: "$6,790",
    goal: "$10.000",
  },
  {
    id: 2,
    image: "../assests/FourthSection/donate-1-2.png",
    imageText: "FOOD",
    heading: "Raise Fund For Clean Healthy Food",
    text: "Street children are poor or home children who live on the streets ",
    percentage: "82",
    raised: "$8,904",
    goal: "$10.000",
  },
  {
    id: 3,
    image: "../assests/FourthSection/donate-1-3.png",
    imageText: "SHELTER",
    heading: "Contribute Make For The Somalians happy",
    text: "Street children are poor or home children who live on the streets ",
    percentage: "32",
    raised: "$4,407",
    goal: "$10.000",
  },
  {
    id: 3,
    image: "../assests/FourthSection/donate-1-4.png",
    imageText: "FOOD",
    heading: "Raise Fund For Clean Healthy Food",
    text: "Street children are poor or home children who live on the streets ",
    percentage: "65",
    raised: "$4,407",
    goal: "$10.000",
  }
];
